### ISSUE TITLE
New commands such as !Agility to load up the Wiki page for the Agility Plugin.

### ISSUE THREAD

**Issue by TomMartow** [devinfrench/runelite-discord-bot#3]
I'm in the process of updating a few wiki pages again, the goal is to simplify them instead of having picture upon picture.

This is what the Agility Wiki page looks like.

-----------------------------------------------------------------------------------------------------

# Agility Configuration

[![Client View](https://thumbs.gfycat.com/BestDismalFantail-size_restricted.gif)](https://gfycat.com/BestDismalFantail)

### 1. Show Lap count

(Default On) Displays in the top-left hand corner your total laps, and laps till level information.

### 2. Hide Lap Count (minutes) [Configurable Box]

(Default 5) This configurable time frame allows the user to choose how long of inactivity to the Agility skill it takes to remove the Agility Infobox.

### 3. Overlay Color [Pick a color]

(Default Green) Here you can choose what colour the overlay is for the entire clickable obstacle.

-----------------------------------------------------------------------------------------------------

The gif is low quality but upon clicking it you are sent to the full quality version on gfycat. Unfortunately, github doesn't allow webm videos. Anyway onto the commands idea.

## !Agility command

> User: !Agility
> RuneLite Bot: https://gfycat.com/BestDismalFantail https://github.com/runelite/runelite/wiki/Agility

Which looks like this:

![image](https://user-images.githubusercontent.com/10462926/39096619-7d34754a-464a-11e8-832f-f66f2b2a4b50.png)

**Comment by MESLewis** [comment]
Also !wiki to link to the main wiki page

**Comment by devLotto** [comment]
Maybe it should be ``!wiki Agility`` instead. 

If it would be !Agility, it'd probably be implemented as such that if you enter an invalid command, it falls back onto sending a wiki link. 
This would have the effect that if you type a command wrong, like ``!isue`` instead of ``!issue``, it would send ``https://github.com/runelite/runelite/wiki/isue`..`

**Comment by devinfrench** [comment]
[Added a ``!wiki`` command.](https://github.com/devinfrench/runelite-discord-bot/commit/3286f0de9b53de69e40467b7fa99dc5cdd3d9a56)
